# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-12-18 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0006_attachment_mimetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='bytes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='post_office.Attachment/bytes/name/mimetype', verbose_name='File'),
        ),
    ]
